- name: Vérifier si Nginx est installé et obtenir sa version
  hosts: test
  tasks:
    - name: Vérifier si Nginx est installé
      command: nginx -v
      register: nginx_version_output
      ignore_errors: yes

    - name: Vérifier la sortie de la commande nginx -v
      debug:
        msg: "Nginx n'est pas installé"
      when: nginx_version_output.failed

    - name: Afficher la version de Nginx
      debug:
        msg: "Version de Nginx: {{ nginx_version_output.stderr }}"
      when: nginx_version_output.rc == 0
